### ISSUE TITLE
LICENSE 里面签名不对

### ISSUE THREAD

**Issue by MegrezZhu** [WangMaoyuan/DM_final#1]
老哥你是从 @Andiedie 那里复制的 LISENCE 模板吗，里面 [第二行](https://github.com/WangMaoyuan/DM_final/blob/2387b6367cb0bb9319ac1d21161bde9a75d6cc90/LICENSE#L3) 名字忘记改啦 :sweat_smile:

**Comment by WangMaoyuan** [comment]
感谢老哥，我这就去看看！

**Comment by WangMaoyuan** [comment]
我的模块复用了他的代码，那这个copyright是不是应该算他的啊其实？

**Comment by MegrezZhu** [comment]
这个 LICENSE 说明的是整个仓库的 copyright 吧，而这个仓库毕竟是你的。至于引用代码的话，一般在注释里说明一下就行，或者在 readme 里给致谢（具体看开源协议，MIT 的话我记得是十分宽松的）

**Comment by WangMaoyuan** [comment]
好的，感谢
